name: workshop

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.12
  - conda-forge::jupyter
  - conda-forge::jupyterlab
  - conda-forge::r-base
  - conda-forge::notebook
  - conda-forge::nbconvert
  - conda-forge::matplotlib
  - conda-forge::pandas
  - pip:
      - nmrglue